config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'home/about'
  get 'home/contact'
  get 'home/pricing'
  get 'home/signup'
  get 'home/registration'
  get 'home/login'
  get 'home/forgot'
  get 'dashboard', to: 'dashboard#index' 
  get 'dashboard/shops'
  get 'dashboard/rewards'
  get 'dashboard/counter'
  get 'dashboard/customers'
  get 'dashboard/settings'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController 
  layout 'back'

  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @header_class = "alt"
    @index_page = true
  end
  def about
    @header_class = ""
    @index_page = false
  end
  def contact
    @header_class = ""
    @index_page = false
  end
  def pricing
    @header_class = ""
    @index_page = false
  end
  def signup
    @header_class = ""
    @index_page = false
  end
  def registration
    @header_class = ""
    @index_page = false
  end
  def login
    @header_class = ""
    @index_page = false
  end
  def forgot
    @header_class = ""
    @index_page = false
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/counter.html.erb
<% content_for :title do %>
  COUNTER
<% end %>
<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <div class="card">
          <div class="card-body">
            <form>
              <div class="row">
                <div class="col-md-12">
                  <div class="form-group">
                    <label class="bmd-label-floating">Customer Phone</label>
                    <input type="text" class="form-control">
                  </div>
                </div>
              </div>
             <button type="submit" class="btn btn-primary pull-left">Search</button>
             <button type="submit" class="btn btn-primary pull-right">Add Stamp</button>
              <div class="clearfix"></div>
            </form>
          </div>
        </div>
      </div>
      <div class="col-md-12">
        <div class="card">
          <div class="card-header card-header-primary">
            <h4 class="card-title ">Stamps</h4>
          </div>
          <div class="card-body">
            <div class="table-responsive">
              <table class="table">
                <thead class=" text-primary">
                  <th>
                    Phone Number
                  </th>
                  <th>
                    Stamps
                  </th>
                  <th>
                  </th>
                </thead>
                <tbody>
                  <tr>
                    <td>
                      627-7894
                    </td>
                    <td>
                      3
                    </td>
                    <td class="text-danger">
                      Delete
                    </td>
                  </tr>
                  <tr>
                    <td>
                      846-2294
                    </td>
                    <td>
                      1
                    </td>
                    <td class="text-danger">
                      Delete
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/dashboard/customers.html.erb
<% content_for :title do %>
  CUSTOMERS
<% end %>
<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <div class="card">
          <div class="card-body">
            <form>
              <button type="submit" class="btn btn-lg btn-primary btn-block">
                Download Customer CSV Data
              </button>
              <div class="clearfix"></div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/dashboard/index.html.erb
<% content_for :title do %>
  MAGIC CARPET
<% end %>
<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-4 col-md-6 col-sm-6">
        <div class="card card-stats">
          <div class="card-header card-header-warning card-header-icon">
            <div class="card-icon">
              <i class="material-icons">face</i>
            </div>
            <p class="card-category">Customers</p>
            <h3 class="card-title">1438
            </h3>
          </div>
          <div class="card-footer">
            <div class="stats">
              <i class="material-icons">face</i> See all customers
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-4 col-md-6 col-sm-6">
        <div class="card card-stats">
          <div class="card-header card-header-success card-header-icon">
            <div class="card-icon">
              <i class="material-icons">verified_user</i>
            </div>
            <p class="card-category">Rewards</p>
            <h3 class="card-title">$34,245</h3>
          </div>
          <div class="card-footer">
            <div class="stats">
              <i class="material-icons">verified_user</i> See all rewards
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-4 col-md-6 col-sm-6">
        <div class="card card-stats">
          <div class="card-header card-header-primary card-header-icon">
            <div class="card-icon">
              <i class="material-icons">thumb_up</i>
            </div>
            <p class="card-category">Stamps</p>
            <h3 class="card-title">13.849</h3>
          </div>
          <div class="card-footer">
            <div class="stats">
              <i class="material-icons">thumb_up</i> See all stamps
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/dashboard/rewards.html.erb
<% content_for :title do %>
  REWARDS
<% end %>
<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <div class="card">
          <div class="card-body">
            <form>
              <div class="row">
                <div class="col-md-12">
                  <div class="form-group">
                    <label class="bmd-label-floating">Reward Plan Name</label>
                    <input type="text" class="form-control">
                  </div>
                </div>
                <div class="col-md-12">
                  <div class="form-group">
                    <label class="bmd-label-floating">Number of Stamps</label>
                    <select class="form-control">
                      <option>1 stamp</option>
                      <option>2 stamps</option>
                      <option>3 stamps</option>
                    </select>
                  </div>
                </div>
              </div>
             <button type="submit" class="btn btn-primary pull-right">Create</button>
              <div class="clearfix"></div>
            </form>
          </div>
        </div>
      </div>
      <div class="col-md-12">
        <div class="card">
          <div class="card-header card-header-primary">
            <h4 class="card-title">Rewards Plans</h4>
          </div>
          <div class="card-body">
            <div class="table-responsive">
              <table class="table">
                <thead class=" text-primary">
                  <th>
                    Name
                  </th>
                  <th>
                    Stamps
                  </th>
                  <th>
                  </th>
                </thead>
                <tbody>
                  <tr>
                    <td>
                      Super Cool
                    </td>
                    <td>
                      5
                    </td>
                    <td class="text-danger">
                      Delete
                    </td>
                  </tr>
                  <tr>
                    <td>
                      Awesome Plan
                    </td>
                    <td>
                      8
                    </td>
                    <td class="text-danger">
                      Delete
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/dashboard/settings.html.erb
<% content_for :title do %>
  SETTINGS
<% end %>
<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <div class="card">
          <div class="card-header card-header-primary">
            <h4 class="card-title ">Settings</h4>
          </div>
          <div class="card-body">
            <form>
              <div class="row">
                <div class="col-md-12">
                  <div class="form-group">
                    <label class="bmd-label-floating">Username</label>
                    <input type="text" class="form-control">
                  </div>
                </div>
                <div class="col-md-12">
                  <div class="form-group">
                    <label class="bmd-label-floating">Phone Number</label>
                    <input type="text" class="form-control">
                  </div>
                </div>
              </div>
             <button type="submit" class="btn btn-primary pull-right">Save</button>
              <div class="clearfix"></div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/dashboard/shops.html.erb
<% content_for :title do %>
  SHOPS
<% end %>
<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <div class="card">
          <div class="card-body">
            <form>
              <div class="row">
                <div class="col-md-12">
                  <div class="form-group">
                    <label class="bmd-label-floating">New Shop</label>
                    <input type="text" class="form-control">
                  </div>
                </div>
              </div>
             <button type="submit" class="btn btn-primary pull-right">Add Shop</button>
              <div class="clearfix"></div>
            </form>
          </div>
        </div>
      </div>
      <div class="col-md-12">
        <div class="card">
          <div class="card-header card-header-primary">
            <h4 class="card-title ">Shops</h4>
          </div>
          <div class="card-body">
            <div class="table-responsive">
              <table class="table">
                <thead class=" text-primary">
                  <th>
                    ID
                  </th>
                  <th>
                    Name
                  </th>
                  <th>
                  </th>
                </thead>
                <tbody>
                  <tr>
                    <td>
                      1
                    </td>
                    <td>
                      Dakota Rice
                    </td>
                    <td class="text-danger">
                      Delete
                    </td>
                  </tr>
                  <tr>
                    <td>
                      2
                    </td>
                    <td>
                      Minerva Hooper
                    </td>
                    <td class="text-danger">
                      Delete
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/about.html.erb
<!-- Main -->
    <section id="main" class="container">
        <header>
            <h2>About onlinepoints.app</h2>
            <p>A product marketeer in a previous life, I want to create a solution to get rid of physical points cards. <br />
            Below picture is my actual unused cards...</p>
        </header>
        <div class="box">
            <span class="image featured"><%= image_tag 'pic01.jpg' %></span>
            <h3>Easy for shops to use</h3>
            <p>Currently I am thinking to implement it such that all customers have to tell the shop owner are their phone numbers.  There are solutions out there already using such method, but ties into CRM or have some limitations.  I am working on beta version now:)</p>
            <div class="row">
                <div class="row-6 row-12-mobilep">
                    <h3>Keep It Simple, Silly:)</h3>
                    <p>No android/iOS app.  All you need is a web-browser to enter points/review points.  Let us make this simple.</p>
                </div>
                <div class="row-6 row-12-mobilep">
                    <h3>Always provide a free version</h3>
                    <p>I am targeting to always have a free version, so that parents who would like to award their kids through points, or businesses that are just starting out and don't have the resources, can utilize the free version.  So far I have not found a free version yet!</p>
                </div>
            </div>
        </div>
    </section>

app/views/home/contact.html.erb
<!-- Main -->
<section id="main" class="container medium">
    <header>
        <h2>Contact Us</h2>
                <p>Are you a shop owner who wish to test out our beta software?<br />
        Or have some ideas you would like us to know?<br />
            Please input your comments here and we will get back to you!</p>
    </header>
    <div class="box">
        <form method="post" action="https://formspree.io/lin.yuchia@gmail.com?subject=Contact form for Online Points App">
            <div class="row gtr-50 gtr-uniform">
                <div class="col-6 col-12-mobilep">
                    <input type="text" name="name" id="name" value="" placeholder="Name" />
                </div>
                <div class="col-6 col-12-mobilep">
                    <input type="email" name="email" id="email" value="" placeholder="Email" />
                </div>
                <div class="col-12">
                    <input type="text" name="subject" id="subject" value="" placeholder="Subject" />
                </div>
                <div class="col-12">
                    <textarea name="message" id="message" placeholder="Enter your message" rows="6"></textarea>
                </div>
                <div class="col-12">
                    <ul class="actions special">
                        <li><input type="submit" value="Send Message" /></li>
                    </ul>
                </div>
            </div>
        </form>
    </div>
</section>

app/views/home/forgot.html.erb
<!-- Main -->
<section id="main" class="container medium">
    <header>
        <h2>Onlinepoints Password Reset</h2>
    </header>
    <div class="box">
        <form method="post" action="">
            <div class="row gtr-50 gtr-uniform">
                <div class="col-12">
                    <input type="email" name="email" id="email" value="" placeholder="Email" />
                </div>
                <div class="col-12">
                    <ul class="actions special">
                        <li><input type="submit" value="Send Reset Instructions" /></li>
                    </ul>
                </div>
            </div>
        </form>
    </div>
</section>

app/views/home/index.html.erb
<!-- Banner -->
    <section id="banner">
    <h2>Unused loyalty points are businesses lost</h2>
    <p>Online points create a win/win scenario for both shops and customers.</p>
    <ul class="actions special">
        <li><a href="#cta" class="button primary">Sign Up As Beta User<a></li>
        <li><a href="#features" class="button">Learn More</a></li>
    </ul>
    </section>

<!-- Main -->
    <section id="main" class="container">

    <section class="box special">
        <header class="major">
        <h2>Introducing the ultimate online points app
        <br />
        for customer loyalty</h2>
        <p>Ever wondered why customers never use your physical loyalty points cards?<br />
        They are easy to get lost, bulky inside your wallet, and points are hard to track.<br />
        Why not sign up to be a beta tester for our online points (for free)?</p>
                                        
        </header>
    
    <!--
        // no need for pictures here
        <span class="image featured"><img src="images/pic01.jpg" alt="" /></span>

    -->

    </section>

    <section id="features" class="box special features">
        <div class="features-row">
        <section>
            <span class="icon major fa fa-bolt accent2"></span>
            <h3>Swift deployment</h3>
            <p>As a shop owner, it only takes 5 minutes and a web-browser to set up.</p>
        </section>
        <section>
            <span class="icon major fa-area-chart accent3"></span>
            <h3>Customized campaign</h3>
            <p>You can create customized loyalty program that fits into your marketing campaign.</p>
        </section>
        </div>
        <div class="features-row">
        <section>
            <span class="icon major fa-cloud accent4"></span>
            <h3>Easy Aggregation</h3>
            <p>Since all points are online, there are no more lost cards.  Shop owners only need a computer (or a tablet) to give customers points.</p>
        </section>
        <section>
            <span class="icon major fa-lock accent5"></span>
            <h3>Detailed reporting</h3>
            <p>Currently we are considering using either email or phone number to create customers' online point cards.  Your feedback is greatly appreciated!</p>
        </section>
        </div>
    </section>

    </section>

<!-- CTA -->
    <section id="cta">

    <h2>Sigu up for beta access</h2>
    <p>Are you a resturant/shop owner who wants to have a marketing campaign but doesn't have the marketing budget?<br />
    Sign up for our beta testing, and test your marketing campaign here(for free)!</p>

    <form method="post" action="https://formspree.io/lin.yuchia@gmail.com?subject=I Want To be a Online Points Beta Bester&body=Sign Up for beta access">
        <div class="row gtr-50 gtr-uniform">
        <div class="col-8 col-12-mobilep">
            <input type="email" name="email" id="email" placeholder="Enter your email here" />
        </div>
        <div class="col-4 col-12-mobilep">
            <input type="submit" value="Sign Up" class="fit" />
        </div>
        </div>
    </form>

    </section>

app/views/home/login.html.erb
<!-- Main -->
<section id="main" class="container medium">
    <header>
        <h2>Onlinepoints Login</h2>
    </header>
    <div class="box">
        <form method="post" action="">
            <div class="row gtr-50 gtr-uniform">
                <div class="col-12">
                    <input type="email" name="email" id="email" value="" placeholder="Email" />
                </div>
                <div class="col-12">
                    <input type="text" name="password" id="password" value="" placeholder="Password" />
                </div>
                <div class="col-12">
                    <ul class="actions special">
                        <li><input type="submit" value="Login" /></li>
                    </ul>
                </div>
            </div>
        </form>
    </div>
</section>

app/views/home/pricing.html.erb
<section id="main" class="container">
    <div class="row">
        <div class="col-4 col-11-narrower">
            <section class="box special">
               <span class="icon major fa-bicycle accent2"></span>
                <h3>Free Plan</h3>

                <ul class="alt">
                    <li>Feature 1</li>
                    <li>Feature 2</li>
                    <li>Feature 3</li>
                </ul>
                <%= link_to 'Select', home_registration_path, class:"button"%>
            </section>
        </div>
        <div class="col-4 col-11-narrower">
            <section class="box special">
                <span class="icon major fa-plane accent3"></span>
                <h3>Profesional Editon</h3>
                <ul class="alt">
                    <li>Feature 1</li>
                    <li>Feature 2</li>
                    <li>Feature 3</li>
                </ul>
                <%= link_to 'Select', home_contact_path, class:"button"%>
            </section>
        </div>
        <div class="col-4 col-11-narrower">
            <section class="box special">
                <span class="icon major fa-rocket accent4"></span>
                <h3>Enterprise Edition</h3>
                <ul class="alt">
                    <li>Feature 1</li>
                    <li>Feature 2</li>
                    <li>Feature 3</li>
                </ul>
                <%= link_to 'Select', home_contact_path, class:"button"%>
            </section>
        </div>
    </div>
</section>

app/views/home/registration.html.erb
<!-- Main -->
<section id="main" class="container medium">
    <header>
        <h2>Build Customer loyalty the easy way</h2>
                <p>Sign up for your free Plan to start getting customers comming back.<br />
        No credit card needed!!<br />
    </header>
    <div class="box">
        <form method="post" action="">
            <div class="row gtr-50 gtr-uniform">
                <div class="col-12">
                    <input type="email" name="email" id="email" value="" placeholder="Email" />
                </div>
                <div class="col-12">
                    <input type="text" name="password" id="password" value="" placeholder="Password (minimum 8 chars)" />
                </div>
                <div class="col-12">
                    <ul class="actions special">
                        <li><input type="submit" value="Sign Me Up" /></li>
                    </ul>
                </div>
            </div>
        </form>
    </div>
</section>

app/views/home/signup.html.erb
<!-- Main -->
<section id="main" class="container medium">
    <header>
        <h2>Onlinepoints Registration</h2>
    </header>
    <div class="box">
        <form method="post" action="">
            <div class="row gtr-50 gtr-uniform">
                <div class="col-12">
                    <input type="email" name="email" id="email" value="" placeholder="Email" />
                </div>
                <div class="col-12">
                    <input type="text" name="password" id="password" value="" placeholder="Password" />
                </div>
                <div class="col-12">
                  <input type="text" name="store" id="store" value="" placeholder="Store Name" />
                </div>
                <div class="col-12">
                    <ul class="actions special">
                        <li><input type="submit" value="Register" /></li>
                    </ul>
                </div>
            </div>
        </form>
    </div>
</section>

app/views/layouts/_back_footer.html.erb
<footer class="footer">
  <div class="container-fluid">
    <div class="copyright float-right">
      &copy;
      <script>
        document.write(new Date().getFullYear())
      </script> <a href="/" target="_blank">Online Points</a>
    </div>
  </div>
</footer>

app/views/layouts/_bodytag.html.erb
<% if @index_page %>
  <body class="landing is-preload">
<% else %>
  <body class="is-preload">
<% end %>

app/views/layouts/_dashboard_header.html.erb
<% if @header_class != '' %>
    <header id="header" class="alt">
<% else %>
    <header id="header">
<% end %>
    <nav id="nav">
        <ul>
            <li><%= link_to 'Shops', dashboard_shops_path%></li>
            <li><%= link_to 'Counter', dashboard_counter_path%></li>
            <li><%= link_to 'Rewards', dashboard_rewards_path%></li>
            <li><%= link_to 'Customers', dashboard_customer_path%></li>
            <li><%= link_to 'Settings', dashboard_settings_path%></li>
            <li><%= link_to 'Logout', root_path%></li>
    </nav>
</header>

app/views/layouts/_footer.html.erb
    
      <footer id="footer">
        <ul class="copyright">
          <li>&copy; &nbsp; 2019 &nbsp; onlinepoints.app &nbsp;    All rights reserved.</li>
        </ul>
      </footer>

app/views/layouts/_header.html.erb
<% if @header_class != '' %>
    <header id="header" class="alt">
<% else %>
    <header id="header">
<% end %>
    <nav id="nav">
        <ul>
            <li><%= link_to 'Home', root_path%></li>
            <li>
                <a href="#" class="icon fa-angle-down">Questions?</a>
                <ul>
                    <li><%= link_to 'About',   home_about_path   %></li>
                    <li><%= link_to 'Contact', home_contact_path %></li>
                    <li><%= link_to 'Pricing', home_pricing_path %></li>
                </ul>
            </li>
            <li><%= link_to 'Sign Up', home_signup_path %></li>
            <li><%= link_to 'Login',   home_login_path  %></li>
        </ul>
    </nav>
</header>

app/views/layouts/_navbar.html.erb
 <!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top ">
  <div class="container-fluid">
    <div class="navbar-wrapper">
      <a class="navbar-brand"><%= content_for :title%></a>
    </div>
    <button class="navbar-toggler" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
      <span class="sr-only">Toggle navigation</span>
      <span class="navbar-toggler-icon icon-bar"></span>
      <span class="navbar-toggler-icon icon-bar"></span>
      <span class="navbar-toggler-icon icon-bar"></span>
    </button>
  </div>
</nav>
<!-- End Navbar -->

app/views/layouts/_sidebar.html.erb
<div class="sidebar" data-color="purple" data-background-color="white" data-image="../assets/img/sidebar-1.jpg">
  <!--
    Tip 1: You can change the color of the sidebar using: data-color="purple | azure | green | orange | danger"

    Tip 2: you can also add an image using data-image tag
-->
  <div class="logo">
    <a href="/" class="simple-text logo-normal">
      Online Points
    </a>
  </div>
  <div class="sidebar-wrapper">
    <ul class="nav">
      <li class="nav-item ">
        <a class="nav-link" href="/dashboard">
          <i class="material-icons">dashboard</i>
          <p>Dashboard</p>
        </a>
      </li>
      <li class="nav-item ">
        <a class="nav-link" href="/dashboard/shops">
          <i class="material-icons">store</i>
          <p>Shops</p>
        </a>
      </li>
      <li class="nav-item ">
        <a class="nav-link" href="/dashboard/counter">
          <i class="material-icons">thumb_up</i>
          <p>Counter</p>
        </a>
      </li>
      <li class="nav-item ">
        <a class="nav-link" href="/dashboard/rewards">
          <i class="material-icons">verified_user</i>
          <p>Rewards</p>
        </a>
      </li>
      <li class="nav-item ">
        <a class="nav-link" href="/dashboard/customers">
          <i class="material-icons">face</i>
          <p>Customers</p>
        </a>
      </li>
      <li class="nav-item ">
        <a class="nav-link" href="/dashboard/settings">
          <i class="material-icons">settings</i>
          <p>Settings</p>
        </a>
      </li>
      <li class="nav-item ">
        <a class="nav-link" href="/">
          <i class="material-icons">logout</i>
          <p>Logout</p>
        </a>
      </li>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Online Points Application</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
		
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <%= render 'layouts/bodytag' %>
  
  <div id="page-wrapper">
    <%= render 'layouts/header' %>

    <%= yield %>

    <%= render 'layouts/footer' %>
  </div>
  <%= javascript_include_tag 'vendors', 'data-turbolinks-track': 'reload' %>
</body>
</html>